<img src="https://d24cdstip7q8pz.cloudfront.net/t/ineuron1/content/common/images/final%20logo.png" height=60 alt-text="iNeuron.ai logo">

## 17.1 Numpy Array and Methods

`NumPy` array is N-dimensional array object, or ndarray, which
is a used for large data sets. It will helps to perform mathematical operation on the huge datasets.

In [ ]:
import numpy as np # importing numpy array
type(np.array(["vbhvh", 2, 3])) # type of numpy array is ndarray

numpy.ndarray

In [ ]:
#Upcasting:

In [ ]:
np.array([1, 2, 3.0]) # If any float data exists, then int will convert to float called upcasting

array([1., 2., 3.])

In [ ]:
#two dimensions

In [ ]:
 np.array([[1, 2], [3, 4]]) # 2-d array

array([[1, 2],
       [3, 4]])

In [ ]:
#Minimum dimensions 2:

In [ ]:
np.array([1, 2, 3], ndmin=5) # ndimn will define minimum dimension in array

array([[[[[1, 2, 3]]]]])

In [ ]:
#dtype

In [ ]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#Data-type consisting of more than one element:

In [ ]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [ ]:
type(x[1][0])

numpy.int16

In [ ]:

#Creating an array from sub-classes:

In [ ]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [ ]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

### numpy.asarray

In [ ]:
#Convert the input to an array.

In [ ]:
#Convert a list into an array:

In [ ]:
 a = [1, 2]
type(a)

list

In [ ]:
type(np.asarray(a))

numpy.ndarray

In [ ]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [ ]:
np.asarray((1,2))

array([1, 2])

In [ ]:
#If dtype is set, array is copied only if dtype does not match:

In [ ]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [ ]:
np.asarray([1,2]) is a

False

In [ ]:
np.asarray([1,2])

array([1, 2])

In [ ]:
np.asarray(a, dtype=np.float64) is a

False

In [ ]:
# ndarray subclasses are not passed through

In [ ]:
issubclass(np.matrix, np.ndarray)

True

In [ ]:
a = np.matrix([[1, 2]])
np.asanyarray(a)


matrix([[1, 2]])

In [ ]:
np.asarray(a) is a

False

In [ ]:
type(np.asarray(a))

numpy.ndarray

### numpy.asanyarray

In [ ]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [ ]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [ ]:
np.asanyarray([1,2]) is a

False

### numpy.copy

In [ ]:
np.array(a, copy=True)  

array([[1, 2]])

In [ ]:
#Create an array x, with a reference y and a copy z:

In [ ]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [ ]:
y = x

In [ ]:
z = np.copy(x)

In [ ]:
y[0] = 100
x

array([100,   2,   3])

In [ ]:
x

array([100,   2,   3])

In [ ]:
id(x[0])

2148139021616

In [ ]:
id(y[0])

2148139021968

In [ ]:
id(x) 

2148139202960

In [ ]:
id(y)

2148139202960

### numpy.fromfunction

In [ ]:
#Construct an array by executing a function over each coordinate.

In [ ]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int) # using lambda function

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [ ]:
#Create a new 1-dimensional array from an iterable object.

In [ ]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001F4271B1B48>

In [ ]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
#A new 1-D array initialized from text data in a string

In [ ]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [ ]:
np.fromstring('1, 2', dtype=int, sep=',') # using sep as ","

array([1, 2])

In [ ]:
# How to create a record array from a (flat) list of arrays

In [ ]:
x1=np.array([1,2,3,4])

In [ ]:
x2=np.array(['a','dd','xyz','12'])

In [ ]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [ ]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [ ]:
print(r[1]["a"])

2


x1[1]=34

In [ ]:
x1[1]

2

## 17.2 data types in numpy

In [ ]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [ ]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [ ]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


## 17.3 More numpy methods

### arange and linspace

In [ ]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high with step size as 2.3

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [ ]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [ ]:
list(range(50,-1,5))

[]

In [ ]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [ ]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [ ]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [ ]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


### Matrix creation

In [ ]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [ ]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [ ]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [ ]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [ ]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [ ]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [ ]:
np.arange(3,7,2)

array([3, 5])

In [ ]:
np.linspace(2.0, 3.0, num=5) # num= specify total number of elements in numpy array

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False) # endpoint= False will not include end number

array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
np.linspace(2.0, 3.0, num=9, retstep=True) # retstep will return the step size aswell

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [ ]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [ ]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [ ]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [ ]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [ ]:
#Extract a diagonal or construct a diagonal array.

In [ ]:
x = np.arange(16).reshape((-1,4))

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.diag(x)

array([ 0,  5, 10, 15])

In [ ]:
np.diag(x, k=2) # k=2 means diagonal elements from row and column from index 2

array([2, 7])

In [ ]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [ ]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [ ]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [ ]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [ ]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [ ]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [ ]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [ ]:
#return a Lower triangle of an array.

In [ ]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [ ]:
#return Upper triangle of an array.

In [ ]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

### Random number generation

In [ ]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.57206881 0.18750478 0.21470566]
 [0.91180757 0.4613888  0.91902704]]


In [ ]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.27802424 -0.0212869  -0.85610822]
 [ 0.00246231  0.60716183 -1.02811062]
 [-0.03618774  0.25766332  1.22863825]
 [-0.4149398   0.26254548  0.76560076]]


In [ ]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector: 6

Random integer matrix


In [ ]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[ 5 34 72 76]
 [94  8  8 47]
 [52 32 28 32]
 [22 16 27 87]]

20 samples drawn from a dice throw: [1 3 1 3 6 5 5 5 1 6 6 5 4 3 5 5 5 6 6 5]


### Reshaping

In [ ]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[43, 96, 80, 98, 94],
       [ 4, 67, 60, 89, 83],
       [59, 79, 37, 58, 20],
       [39, 13, 11, 21, 32],
       [41, 84, 31, 14, 90],
       [69, 53, 24, 11, 15]])

In [ ]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [ ]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [43 96 80 98 94  4 67 60 89 83 59 79 37 58 20 39 13 11 21 32 41 84 31 14
 90 69 53 24 11 15] 
 --------------------

b looks like
 -------------------- 
 [[[43 96 80 98 94]
  [ 4 67 60 89 83]
  [59 79 37 58 20]]

 [[39 13 11 21 32]
  [41 84 31 14 90]
  [69 53 24 11 15]]] 
 --------------------

c looks like
 -------------------- 
 [[43 96 80 98 94]
 [ 4 67 60 89 83]
 [59 79 37 58 20]
 [39 13 11 21 32]
 [41 84 31 14 90]
 [69 53 24 11 15]] 
 --------------------


In [ ]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [ 8 44 83 93 49 81 39 75 40 25]

Here is the sorted vector
 -------------------------------------------------- 
 [ 8 25 39 40 44 49 75 81 83 93]


In [ ]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[36 41 59 69 74]
 [ 7 10 18 33 47]
 [12 39 50 79 89]
 [ 5 21 23 27 68]
 [ 4 30 66 79 80]]


array([[59, 69, 36, 74, 41],
       [ 7, 10, 18, 33, 47],
       [12, 39, 50, 79, 89],
       [68, 27,  5, 21, 23],
       [ 4, 79, 66, 80, 30]])

In [ ]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 89
Max of b: 98


array([[[43, 96, 80, 98, 94],
        [ 4, 67, 60, 89, 83],
        [59, 79, 37, 58, 20]],

       [[39, 13, 11, 21, 32],
        [41, 84, 31, 14, 90],
        [69, 53, 24, 11, 15]]])

In [ ]:
M

array([[59, 69, 36, 74, 41],
       [ 7, 10, 18, 33, 47],
       [12, 39, 50, 79, 89],
       [68, 27,  5, 21, 23],
       [ 4, 79, 66, 80, 30]])

In [ ]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: [3 4 4 0 3]
Max of b location: 3
Max of c location: 3


### Indexing and slicing

In [ ]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [ ]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [ ]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [ ]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


3 Elements from last backwards are: []


In [ ]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [ ]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[90 76 88 52 96]
 [94 72 14 47 76]
 [23 54 28 31 34]]


array([[76, 52],
       [72, 47],
       [54, 31]])

In [ ]:
mat[0:3,[1,3]]
mat

array([[90, 76, 88, 52, 96],
       [94, 72, 14, 47, 76],
       [23, 54, 28, 31, 34]])

In [ ]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 72


array([[90, 76, 88, 52, 96],
       [94, 72, 14, 47, 76],
       [23, 54, 28, 31, 34]])

In [ ]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 14

Row or column extract
----------------------


In [ ]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [23 54 28 31 34]
Entire column at index 3: [52 47 31]


In [ ]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[47 76]
 [31 34]]


In [ ]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[76 52]
 [72 47]]


### Subseting

In [ ]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[78 38 67 60 24]
 [49 78 73 85 90]
 [33 72 97 93 15]]


array([[ True, False,  True,  True, False],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True, False]])

In [ ]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [78 67 60 78 73 85 90 72 97 93]


### Slicing

In [ ]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [ ]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [ ]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [ ]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [ ]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [ ]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Universal Functions

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[9 6 6]
 [5 3 9]
 [3 2 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[5 5 7]
 [8 5 9]
 [4 1 7]]


In [ ]:
mat1*mat2

array([[45, 30, 42],
       [40, 15, 81],
       [12,  2, 56]])

In [ ]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[117  81 159]
 [ 85  49 125]
 [ 63  33  95]]


In [ ]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[109 106 106]
 [105 103 109]
 [103 102 108]]


In [ ]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[729 216 216]
 [125  27 729]
 [ 27   8 512]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[729 216 216]
 [125  27 729]
 [ 27   8 512]]


### Broadcasting

NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
In the simplest case, the two arrays must have exactly the same shape.
NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
dimensions, and works its way forward. Two dimensions are compatible when
they are equal, or one of them is 1

In [ ]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [ ]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [ ]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [ ]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [ ]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [ ]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


### Array Math

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[9 4 2]
 [8 6 5]
 [7 3 8]]

2nd Matrix of random single-digit numbers
------------
 [[3 5 6]
 [8 4 8]
 [1 7 6]]


In [ ]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[3.         2.         1.41421356]
 [2.82842712 2.44948974 2.23606798]
 [2.64575131 1.73205081 2.82842712]]


In [ ]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[8.10308393e+03 5.45981500e+01 7.38905610e+00]
 [2.98095799e+03 4.03428793e+02 1.48413159e+02]
 [1.09663316e+03 2.00855369e+01 2.98095799e+03]]


In [ ]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.95424251 0.60205999 0.30103   ]
 [0.90308999 0.77815125 0.69897   ]
 [0.84509804 0.47712125 0.90308999]]
[[9 4 2]
 [8 6 5]
 [7 3 8]]
[[3 5 6]
 [8 4 8]
 [1 7 6]]


In [ ]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[0 4 2]
 [0 2 5]
 [0 3 2]]


array([[0, 4, 2],
       [0, 2, 5],
       [0, 3, 2]], dtype=int32)

In [ ]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [ ]:
A = np.linspace(0,12*np.pi,1001)


In [ ]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])